# Set up Traefik routers and services
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress-api
  namespace: applications
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: clusterissuer
    # For some reason, it was not possible to configure middleware for only one route
    traefik.ingress.kubernetes.io/router.middlewares: applications-cors-middleware@kubernetescrd
spec:
  rules:
    - host: test-subdomain-5-api.prototyping.quest
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 8000
  tls:
    - secretName: api-service-cert
      hosts:
        - test-subdomain-5-api.prototyping.quest
---
# Set up CORS middleware
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cors-middleware
  namespace: applications
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "POST"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - "https://test-subdomain-5.prototyping.quest"
    accessControlMaxAge: 86400 # How much will the preflight response (allowed methods and headers) be cached for, in seconds
    addVaryHeader: true # The browser caches what it knows about the API. It makes sense to let the browser know that the response may differ depending on the origin.
---
# Set up Traefik routers and services
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: applications
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: clusterissuer
spec:
  rules:
    - host: test-subdomain-5.prototyping.quest
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 80
  tls:
    - secretName: web-service-cert
      hosts:
        - test-subdomain-5.prototyping.quest
