apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: applications
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: api-service
      app.kubernetes.io/part-of: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-service
        app.kubernetes.io/part-of: app
    spec:
      containers:
        - name: api
          image: ghcr.io/managed-prototypes/fullstack-k8s-backend:latest
          imagePullPolicy: IfNotPresent
          # Note: cheap nodes may have problems with resources
          # resources:
          #   limits:
          #     memory: 128Mi
          #     cpu: "0.2"
          #   requests:
          #     memory: 128Mi
          #     cpu: "0.2"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: applications
  name: api-service
spec:
  selector:
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
